services:
# Listener
    oka_cors.request.event_listener:
        class: Oka\CORSBundle\EventListener\RequestListener
        arguments: [[]]
        tags:
          - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
          - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 255}
